### ISSUE TITLE
Understanding outputstreams | 12th Feb 2025 | 6pm

### ISSUE THREAD

**Issue by rkpatra201** [Jena-Biswajit/learning-project-01-learning-tracker-201#18]
We have dfnt types of output streams. 
Why we need output streams.
Can we list down the purpose of each of them.

Add link to .md file as comment here. @Jena-Biswajit

**Comment by Jena-Biswajit** [comment]
@rkpatra201 I have pushed the updated file for above given task on (bugfix/file-handling/src/main/java/Resourses/outputstream.md ) location . please review it and let me know anything to improve .

**Comment by rkpatra201** [comment]
I see here also you missed the link to outputstream.md file. I understand the path but if I just paste above path in url it wont work. So provide a link of file always which can be open directly.
